### ISSUE TITLE
Crazy idea: unix piping

### ISSUE THREAD

**Issue by ashaffer** [weo-edu/store#6]
```
nsq --channel user | node stores/user | dequeue
```

(presuming that the store outputs event ids that it handles successfully, dequeue then removes them from the queue)

This gets us other sources for free:

``` javascript
cat log/* | node stores/index.js
```

It also gets us low-memory streaming for free (I think the OS would just handle this transparently).  Errors might be a little tricky, but we could probably figure it out, maybe making a logging command that just passes through its stdout to the next thing.

**Comment by ashaffer** [comment]
It seems by default errors are taken out of the primary stream and redirected to the console,

http://en.wikipedia.org/wiki/Pipeline_%28Unix%29#Error_stream

```
nsq --channel user | node stores/user 2>> errolog | dequeue
```

So it is technically feasible to do this if we want to.  Although at the moment it appears piping output on the shell is broken in node and iojs:

https://github.com/iojs/io.js/issues/947

**Comment by joshrtay** [comment]
Ya. This looks awesome.

**Comment by joshrtay** [comment]
should it be more like `nsq_to_json | json_to_store`?

like tj's example:

```
phony < log.json  | json_to_nsq --topic logs
```

**Comment by joshrtay** [comment]
how would dequeue work? is that possible?

shouldn't errors go to stderr?

**Comment by ashaffer** [comment]
In regards to tj's example, that seems good.  So `json_to_store` abstracts the streaming json from text and dispatch stuff?  So the full command would be like:

`nsq_to_json --channel user | json_to_store stores/user.js`
?

In regards to dequeue, I was thinking that `json_to_store` would emit the id's of the events that it handles successfully to `stdout`, and dequeue would consume those.

**Comment by ashaffer** [comment]
We'll probably have to do this as well:

http://unix.stackexchange.com/questions/25372/turn-off-buffering-in-pipe

We'll also probably want to run some tests to see if this increases latency significantly.  I think as long as we handle the buffering correctly the latency shouldn't be a big deal, but not sure how much control we'll have there.

**Comment by joshrtay** [comment]
closing in favor of `nsq_to_lambda` and `json_to_lambda`
